# Generated by Django 3.2.13 on 2022-12-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('new_link', models.URLField(default='')),
                ('expire', models.DateTimeField()),
            ],
        ),
    ]
